MLOPS-289: Add MS2Deep class to call the endpoint
omigami/omigami pull request #23
Opened 2021-06-16 20:27 UTC by dianacarvalho1

[Issue](https://datarevenue.atlassian.net/browse/MLOPS-289)

Add unit tests for it

Some methods are just "templates" from the Spec2Vec since it is not yet 100% clear how the inputs and the output of the endpoint will look like

--- don't change below this line ---
MLOPS-289 <#DTT#>

2021-06-18 09:29 UTC, tamaralipows requested changes
Hey @dianacarvalho1, this looks good, just some minor comments, I think we just need to coordinate with each other about the format of the payload so our PRs match on the client and core side. :)

2021-06-18 09:29 UTC, tamaralipows commented on omigami/ms2deep.py
> +                    "parameters": [],  # maybe there will be some later on
I think these are better off as curly braces `{}` since we will probably check for kwargs

2021-06-18 09:29 UTC, tamaralipows commented on omigami/ms2deep.py
> +                    "peaks_json": str(
I guess we need to coordinate on how we are sending the payload. On my side I have specified a list of dicts of `mz` and `intensity` (I guess it's more readable than list indexing). We could do it either way though - do you have any strong opinion? 

Also is it super necessary to specify `peaks_json` or can we get straight to the point (mz, intensity)?  Are we expecting that there might be more keys in this spectrum dict?

2021-06-18 09:29 UTC, tamaralipows commented on omigami/ms2deep.py
> +                        "of a list or a list. Passed value: {spectrum['peaks_json']}",
Need to format this string using `f"` :)

2021-06-22 09:55 UTC, tamaralipows approved these changes
Yay it's great. Only one non mandatory suggestion

2021-06-22 09:55 UTC, tamaralipows commented on tests/test_ms2deep_client.py
> +                        "peaks_json": "[[80.060677, 157.0], [337.508301, 230.0]]",
Maybe also change it here just for consistency, even though I know in this case it doesn't matter because we are testing the bad token :))

2021-06-23 09:15 UTC, tamaralipows commented on omigami/ms2deepscore.py
> +        return {"Tanimoto Score:": response["jsonData"]}
Duplicate colon?

2021-06-28 16:53 UTC, pedrocwb approved these changes

2021-06-28 17:05 UTC, merged